# Header
menu:
  Home: /
  Archives: /archives
  About: /about
# Header Icon
menu_icon:
  Home: nav-home-icon
  Archives: nav-archives-icon
  About: nav-about-icon

rss: /atom.xml

# Content
excerpt_link: ">> Read More..."
archive_yearly: false #按年存档

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll 友情链接
blogrolls:
  - 泰然网: http://tairan.com
  - cocos官网: http://cocos.com

fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
duoshuo_shortname: gameeer